import CartItem from '@/components/navbar/CartItem';
import CartProvider from '@/context/CartProvider';
import { Poppins } from 'next/font/google';
import Image from 'next/image';
import Link from 'next/link';
import './globals.css';

const poppins = Poppins({
  weight: ['400', '500', '600', '800'],
  subsets: ['latin'],
  display: 'swap',
});

export const metadata = {
  title: 'Yantun Khaijan',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className} antialiased`}
        cz-shortcut-listen="true"
      >
        <CartProvider>
          <header className="px-5 py-2 flex  items-center justify-between gap-5 bg-stone-800">
            <Link href="/">
              <Image
                src="/assets/logo.png"
                alt=""
                className="w-30"
                width={120}
                height={120}
              />
            </Link>

            <div className="space-x-5">
              <Link className="btn" href="/foods">
                Food
              </Link>
              <Link className="btn" href="/reviews">
                Reviews
              </Link>
              <CartItem />
            </div>
          </header>

          <main className="px-5 py-8">{children}</main>
        </CartProvider>
      </body>
    </html>
  );
}
