import CartProvider from '@/context/CartProvider';
import { Geist, Geist_Mono } from 'next/font/google';
import Link from 'next/link';
import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata = {
  title: 'Yantun Khaijan',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <CartProvider>
          <header className="px-5 py-2 flex  items-center justify-between gap-5 bg-stone-800">
            <Link href="/">
              <img src="/assets/logo.png" alt="" className="w-[120px]" />
            </Link>

            <div className="space-x-5">
              <Link className="btn" href="/foods">
                Food
              </Link>
              <Link className="btn" href="/reviews">
                Reviews
              </Link>
              <span className="btn" href="/reviews">
                Cart <sup>0</sup>
              </span>
            </div>
          </header>

          <main className="px-5 py-8">{children}</main>
        </CartProvider>
      </body>
    </html>
  );
}
